// Generated from public HealthKit SDK headers. Regenerate with Scripts/generate-health-catalog.mjs.
// Includes 209 identifier-based types; specialized types are added by HealthTypeCatalog.
import HealthKit

extension HealthTypeCatalog {
    static func appendSDKTypes(_ append: (HKObjectType?, Family) -> Void) {
        if #available(iOS 16.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierAppleSleepingWristTemperature")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierBodyFatPercentage")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierBodyMass")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierBodyMassIndex")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierElectrodermalActivity")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierHeight")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierLeanBodyMass")), .quantity) }
        if #available(iOS 11.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierWaistCircumference")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierActiveEnergyBurned")), .quantity) }
        if #available(iOS 9.3, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierAppleExerciseTime")), .quantity) }
        if #available(iOS 14.5, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierAppleMoveTime")), .quantity) }
        if #available(iOS 13.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierAppleStandTime")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierBasalEnergyBurned")), .quantity) }
        if #available(iOS 18.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierCrossCountrySkiingSpeed")), .quantity) }
        if #available(iOS 17.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierCyclingCadence")), .quantity) }
        if #available(iOS 17.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierCyclingFunctionalThresholdPower")), .quantity) }
        if #available(iOS 17.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierCyclingPower")), .quantity) }
        if #available(iOS 17.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierCyclingSpeed")), .quantity) }
        if #available(iOS 18.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDistanceCrossCountrySkiing")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDistanceCycling")), .quantity) }
        if #available(iOS 11.2, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDistanceDownhillSnowSports")), .quantity) }
        if #available(iOS 18.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDistancePaddleSports")), .quantity) }
        if #available(iOS 18.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDistanceRowing")), .quantity) }
        if #available(iOS 18.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDistanceSkatingSports")), .quantity) }
        if #available(iOS 10.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDistanceSwimming")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDistanceWalkingRunning")), .quantity) }
        if #available(iOS 10.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDistanceWheelchair")), .quantity) }
        if #available(iOS 18.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierEstimatedWorkoutEffortScore")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierFlightsClimbed")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierNikeFuel")), .quantity) }
        if #available(iOS 18.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierPaddleSportsSpeed")), .quantity) }
        if #available(iOS 17.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierPhysicalEffort")), .quantity) }
        if #available(iOS 10.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierPushCount")), .quantity) }
        if #available(iOS 18.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierRowingSpeed")), .quantity) }
        if #available(iOS 16.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierRunningPower")), .quantity) }
        if #available(iOS 16.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierRunningSpeed")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierStepCount")), .quantity) }
        if #available(iOS 10.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierSwimmingStrokeCount")), .quantity) }
        if #available(iOS 16.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierUnderwaterDepth")), .quantity) }
        if #available(iOS 18.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierWorkoutEffortScore")), .quantity) }
        if #available(iOS 13.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierEnvironmentalAudioExposure")), .quantity) }
        if #available(iOS 16.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierEnvironmentalSoundReduction")), .quantity) }
        if #available(iOS 13.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierHeadphoneAudioExposure")), .quantity) }
        if #available(iOS 16.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierAtrialFibrillationBurden")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierHeartRate")), .quantity) }
        if #available(iOS 16.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierHeartRateRecoveryOneMinute")), .quantity) }
        if #available(iOS 11.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierHeartRateVariabilitySDNN")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierPeripheralPerfusionIndex")), .quantity) }
        if #available(iOS 11.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierRestingHeartRate")), .quantity) }
        if #available(iOS 11.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierVO2Max")), .quantity) }
        if #available(iOS 11.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierWalkingHeartRateAverage")), .quantity) }
        if #available(iOS 15.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierAppleWalkingSteadiness")), .quantity) }
        if #available(iOS 16.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierRunningGroundContactTime")), .quantity) }
        if #available(iOS 16.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierRunningStrideLength")), .quantity) }
        if #available(iOS 16.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierRunningVerticalOscillation")), .quantity) }
        if #available(iOS 14.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierSixMinuteWalkTestDistance")), .quantity) }
        if #available(iOS 14.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierStairAscentSpeed")), .quantity) }
        if #available(iOS 14.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierStairDescentSpeed")), .quantity) }
        if #available(iOS 14.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierWalkingAsymmetryPercentage")), .quantity) }
        if #available(iOS 14.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierWalkingDoubleSupportPercentage")), .quantity) }
        if #available(iOS 14.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierWalkingSpeed")), .quantity) }
        if #available(iOS 14.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierWalkingStepLength")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDietaryBiotin")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDietaryCaffeine")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDietaryCalcium")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDietaryCarbohydrates")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDietaryChloride")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDietaryCholesterol")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDietaryChromium")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDietaryCopper")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDietaryEnergyConsumed")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDietaryFatMonounsaturated")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDietaryFatPolyunsaturated")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDietaryFatSaturated")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDietaryFatTotal")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDietaryFiber")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDietaryFolate")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDietaryIodine")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDietaryIron")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDietaryMagnesium")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDietaryManganese")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDietaryMolybdenum")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDietaryNiacin")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDietaryPantothenicAcid")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDietaryPhosphorus")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDietaryPotassium")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDietaryProtein")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDietaryRiboflavin")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDietarySelenium")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDietarySodium")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDietarySugar")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDietaryThiamin")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDietaryVitaminA")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDietaryVitaminB12")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDietaryVitaminB6")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDietaryVitaminC")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDietaryVitaminD")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDietaryVitaminE")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDietaryVitaminK")), .quantity) }
        if #available(iOS 9.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDietaryWater")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierDietaryZinc")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierBloodAlcoholContent")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierBloodPressureDiastolic")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierBloodPressureSystolic")), .quantity) }
        if #available(iOS 11.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierInsulinDelivery")), .quantity) }
        if #available(iOS 15.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierNumberOfAlcoholicBeverages")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierNumberOfTimesFallen")), .quantity) }
        if #available(iOS 17.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierTimeInDaylight")), .quantity) }
        if #available(iOS 9.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierUVExposure")), .quantity) }
        if #available(iOS 16.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierWaterTemperature")), .quantity) }
        if #available(iOS 9.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierBasalBodyTemperature")), .quantity) }
        if #available(iOS 18.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierAppleSleepingBreathingDisturbances")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierForcedExpiratoryVolume1")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierForcedVitalCapacity")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierInhalerUsage")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierOxygenSaturation")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierPeakExpiratoryFlowRate")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierRespiratoryRate")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierBloodGlucose")), .quantity) }
        if #available(iOS 8.0, *) { append(HKObjectType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifierBodyTemperature")), .quantity) }
        if #available(iOS 9.0, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierAppleStandHour")), .category) }
        if #available(iOS 14.0, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierEnvironmentalAudioExposureEvent")), .category) }
        if #available(iOS 14.2, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierHeadphoneAudioExposureEvent")), .category) }
        if #available(iOS 12.2, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierHighHeartRateEvent")), .category) }
        if #available(iOS 26.2, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierHypertensionEvent")), .category) }
        if #available(iOS 12.2, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierIrregularHeartRhythmEvent")), .category) }
        if #available(iOS 14.3, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierLowCardioFitnessEvent")), .category) }
        if #available(iOS 12.2, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierLowHeartRateEvent")), .category) }
        if #available(iOS 10.0, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierMindfulSession")), .category) }
        if #available(iOS 15.0, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierAppleWalkingSteadinessEvent")), .category) }
        if #available(iOS 14.0, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierHandwashingEvent")), .category) }
        if #available(iOS 13.0, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierToothbrushingEvent")), .category) }
        if #available(iOS 18.0, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierBleedingAfterPregnancy")), .category) }
        if #available(iOS 18.0, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierBleedingDuringPregnancy")), .category) }
        if #available(iOS 9.0, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierCervicalMucusQuality")), .category) }
        if #available(iOS 14.3, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierContraceptive")), .category) }
        if #available(iOS 16.0, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierInfrequentMenstrualCycles")), .category) }
        if #available(iOS 9.0, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierIntermenstrualBleeding")), .category) }
        if #available(iOS 16.0, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierIrregularMenstrualCycles")), .category) }
        if #available(iOS 14.3, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierLactation")), .category) }
        if #available(iOS 9.0, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierMenstrualFlow")), .category) }
        if #available(iOS 9.0, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierOvulationTestResult")), .category) }
        if #available(iOS 16.0, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierPersistentIntermenstrualBleeding")), .category) }
        if #available(iOS 14.3, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierPregnancy")), .category) }
        if #available(iOS 15.0, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierPregnancyTestResult")), .category) }
        if #available(iOS 15.0, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierProgesteroneTestResult")), .category) }
        if #available(iOS 16.0, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierProlongedMenstrualPeriods")), .category) }
        if #available(iOS 9.0, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierSexualActivity")), .category) }
        if #available(iOS 18.0, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierSleepApneaEvent")), .category) }
        if #available(iOS 8.0, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierSleepAnalysis")), .category) }
        if #available(iOS 13.6, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierAbdominalCramps")), .category) }
        if #available(iOS 13.6, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierAcne")), .category) }
        if #available(iOS 13.6, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierAppetiteChanges")), .category) }
        if #available(iOS 14.0, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierBladderIncontinence")), .category) }
        if #available(iOS 13.6, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierBloating")), .category) }
        if #available(iOS 13.6, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierBreastPain")), .category) }
        if #available(iOS 13.6, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierChestTightnessOrPain")), .category) }
        if #available(iOS 13.6, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierChills")), .category) }
        if #available(iOS 13.6, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierConstipation")), .category) }
        if #available(iOS 13.6, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierCoughing")), .category) }
        if #available(iOS 13.6, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierDiarrhea")), .category) }
        if #available(iOS 13.6, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierDizziness")), .category) }
        if #available(iOS 14.0, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierDrySkin")), .category) }
        if #available(iOS 13.6, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierFainting")), .category) }
        if #available(iOS 13.6, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierFatigue")), .category) }
        if #available(iOS 13.6, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierFever")), .category) }
        if #available(iOS 13.6, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierGeneralizedBodyAche")), .category) }
        if #available(iOS 14.0, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierHairLoss")), .category) }
        if #available(iOS 13.6, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierHeadache")), .category) }
        if #available(iOS 13.6, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierHeartburn")), .category) }
        if #available(iOS 13.6, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierHotFlashes")), .category) }
        if #available(iOS 13.6, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierLossOfSmell")), .category) }
        if #available(iOS 13.6, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierLossOfTaste")), .category) }
        if #available(iOS 13.6, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierLowerBackPain")), .category) }
        if #available(iOS 14.0, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierMemoryLapse")), .category) }
        if #available(iOS 13.6, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierMoodChanges")), .category) }
        if #available(iOS 13.6, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierNausea")), .category) }
        if #available(iOS 14.0, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierNightSweats")), .category) }
        if #available(iOS 13.6, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierPelvicPain")), .category) }
        if #available(iOS 13.6, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierRapidPoundingOrFlutteringHeartbeat")), .category) }
        if #available(iOS 13.6, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierRunnyNose")), .category) }
        if #available(iOS 13.6, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierShortnessOfBreath")), .category) }
        if #available(iOS 13.6, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierSinusCongestion")), .category) }
        if #available(iOS 13.6, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierSkippedHeartbeat")), .category) }
        if #available(iOS 13.6, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierSleepChanges")), .category) }
        if #available(iOS 13.6, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierSoreThroat")), .category) }
        if #available(iOS 14.0, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierVaginalDryness")), .category) }
        if #available(iOS 13.6, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierVomiting")), .category) }
        if #available(iOS 13.6, *) { append(HKObjectType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifierWheezing")), .category) }
        if #available(iOS 14.0, *) { append(HKObjectType.characteristicType(forIdentifier: HKCharacteristicTypeIdentifier(rawValue: "HKCharacteristicTypeIdentifierActivityMoveMode")), .characteristic) }
        if #available(iOS 8.0, *) { append(HKObjectType.characteristicType(forIdentifier: HKCharacteristicTypeIdentifier(rawValue: "HKCharacteristicTypeIdentifierBiologicalSex")), .characteristic) }
        if #available(iOS 8.0, *) { append(HKObjectType.characteristicType(forIdentifier: HKCharacteristicTypeIdentifier(rawValue: "HKCharacteristicTypeIdentifierBloodType")), .characteristic) }
        if #available(iOS 8.0, *) { append(HKObjectType.characteristicType(forIdentifier: HKCharacteristicTypeIdentifier(rawValue: "HKCharacteristicTypeIdentifierDateOfBirth")), .characteristic) }
        if #available(iOS 9.0, *) { append(HKObjectType.characteristicType(forIdentifier: HKCharacteristicTypeIdentifier(rawValue: "HKCharacteristicTypeIdentifierFitzpatrickSkinType")), .characteristic) }
        if #available(iOS 10.0, *) { append(HKObjectType.characteristicType(forIdentifier: HKCharacteristicTypeIdentifier(rawValue: "HKCharacteristicTypeIdentifierWheelchairUse")), .characteristic) }
        if #available(iOS 8.0, *) { append(HKObjectType.correlationType(forIdentifier: HKCorrelationTypeIdentifier(rawValue: "HKCorrelationTypeIdentifierBloodPressure")), .correlation) }
        if #available(iOS 8.0, *) { append(HKObjectType.correlationType(forIdentifier: HKCorrelationTypeIdentifier(rawValue: "HKCorrelationTypeIdentifierFood")), .correlation) }
        if #available(iOS 10.0, *) { append(HKObjectType.documentType(forIdentifier: HKDocumentTypeIdentifier(rawValue: "HKDocumentTypeIdentifierCDA")), .document) }
        if #available(iOS 18.0, *) { append(HKScoredAssessmentType(HKScoredAssessmentTypeIdentifier(rawValue: "HKScoredAssessmentTypeIdentifierGAD7")), .assessment) }
        if #available(iOS 18.0, *) { append(HKScoredAssessmentType(HKScoredAssessmentTypeIdentifier(rawValue: "HKScoredAssessmentTypeIdentifierPHQ9")), .assessment) }
        if #available(iOS 12.0, *) { append(HKObjectType.clinicalType(forIdentifier: HKClinicalTypeIdentifier(rawValue: "HKClinicalTypeIdentifierAllergyRecord")), .clinical) }
        if #available(iOS 16.4, *) { append(HKObjectType.clinicalType(forIdentifier: HKClinicalTypeIdentifier(rawValue: "HKClinicalTypeIdentifierClinicalNoteRecord")), .clinical) }
        if #available(iOS 12.0, *) { append(HKObjectType.clinicalType(forIdentifier: HKClinicalTypeIdentifier(rawValue: "HKClinicalTypeIdentifierConditionRecord")), .clinical) }
        if #available(iOS 12.0, *) { append(HKObjectType.clinicalType(forIdentifier: HKClinicalTypeIdentifier(rawValue: "HKClinicalTypeIdentifierImmunizationRecord")), .clinical) }
        if #available(iOS 12.0, *) { append(HKObjectType.clinicalType(forIdentifier: HKClinicalTypeIdentifier(rawValue: "HKClinicalTypeIdentifierLabResultRecord")), .clinical) }
        if #available(iOS 12.0, *) { append(HKObjectType.clinicalType(forIdentifier: HKClinicalTypeIdentifier(rawValue: "HKClinicalTypeIdentifierMedicationRecord")), .clinical) }
        if #available(iOS 12.0, *) { append(HKObjectType.clinicalType(forIdentifier: HKClinicalTypeIdentifier(rawValue: "HKClinicalTypeIdentifierProcedureRecord")), .clinical) }
        if #available(iOS 12.0, *) { append(HKObjectType.clinicalType(forIdentifier: HKClinicalTypeIdentifier(rawValue: "HKClinicalTypeIdentifierVitalSignRecord")), .clinical) }
        if #available(iOS 14.0, *) { append(HKObjectType.clinicalType(forIdentifier: HKClinicalTypeIdentifier(rawValue: "HKClinicalTypeIdentifierCoverageRecord")), .clinical) }
    }
}
